#!/bin/bash

set -e

echo "Running RSpec suite"

bundle exec rspec spec

for file in `find spec -iname '*_spec.rb'`; do
  echo "Running $file"
  bundle exec rspec $file
done

echo "Running cucumber suite."

bundle exec cucumber
